# -*- coding: utf-8 -*-
"""S.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD6oW5E_v65dCEkVe3sVVSln8K6bTQUl
"""

import numpy as np
import matplotlib.pyplot as plt

def find_peaks(signal):
    maxima = []
    minima = []

    for i in range(1, len(signal) - 1):
        if signal[i] > signal[i - 1] and signal[i] > signal[i + 1]:
            maxima.append(i)
        if signal[i] < signal[i - 1] and signal[i] < signal[i + 1]:
            minima.append(i)

    return maxima, minima

# Load data from text files
data_1 = np.loadtxt('Data_1.txt')
data_2 = np.loadtxt('Data_2.txt')

# Find peaks in the data
maxima_1, minima_1 = find_peaks(data_1)
maxima_2, minima_2 = find_peaks(data_2)

# Function to plot the data and highlight peaks
def plot_signal_with_peaks(signal, maxima, minima, title):
    plt.figure(figsize=(10, 6))
    plt.plot(signal, label='Signal', color='blue')

    # Plot maxima with red dots
    plt.plot(maxima, signal[maxima], 'ro', label='Maxima')

    # Plot minima with blue dots
    plt.plot(minima, signal[minima], 'bo', label='Minima')

    plt.title(title)
    plt.xlabel('Index')
    plt.ylabel('Amplitude')
    plt.legend()
    plt.show()

# Plot for Data_1
plot_signal_with_peaks(data_1, maxima_1, minima_1, "Signal Data 1 with Maxima and Minima")

# Plot for Data_2
plot_signal_with_peaks(data_2, maxima_2, minima_2, "Signal Data 2 with Maxima and Minima")